// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2--9ZJcNriIGSutdlXhL0-e57dQGU7iE',
    appId: '1:24199905100:web:47aad9c4ea318c89c399e9',
    messagingSenderId: '24199905100',
    projectId: 'garage-91551',
    authDomain: 'garage-91551.firebaseapp.com',
    storageBucket: 'garage-91551.appspot.com',
    measurementId: 'G-WD7HEZC1X1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADjGT7bjp4d52SNWEIgoEux0nUMek1s3k',
    appId: '1:24199905100:android:bdebd2ac50959618c399e9',
    messagingSenderId: '24199905100',
    projectId: 'garage-91551',
    storageBucket: 'garage-91551.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr60uYBpJGQTVB0-GSXjRVM4WWxw_sUBs',
    appId: '1:24199905100:ios:65f38ebbf916f705c399e9',
    messagingSenderId: '24199905100',
    projectId: 'garage-91551',
    storageBucket: 'garage-91551.appspot.com',
    iosBundleId: 'com.example.msgarage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr60uYBpJGQTVB0-GSXjRVM4WWxw_sUBs',
    appId: '1:24199905100:ios:1c7bc197bb759bdbc399e9',
    messagingSenderId: '24199905100',
    projectId: 'garage-91551',
    storageBucket: 'garage-91551.appspot.com',
    iosBundleId: 'com.example.msgarage.RunnerTests',
  );
}
